from pathlib import Path

import pandas as pd
import plotly.express as px
from dash import Dash, dcc, html


DATA_PATH = Path(__file__).parent / "data" / "daily_sales_data_2.csv"
PRICE_INCREASE_DATE = pd.Timestamp("2021-01-15")


def load_daily_sales() -> pd.DataFrame:
    """Load and return total daily Pink Morsel sales by date."""
    daily_sales = pd.read_csv(DATA_PATH)

    if {"Date", "Sales"}.issubset(daily_sales.columns):
        # Support pre-aggregated data generated by the prior task.
        working = daily_sales[["Date", "Sales"]].copy()
        working["Date"] = pd.to_datetime(working["Date"], format="mixed", errors="coerce")
        grouped_sales = (
            working.dropna(subset=["Date"]).groupby("Date", as_index=False)["Sales"].sum().sort_values("Date")
        )
    else:
        # Support raw row-level data by deriving Pink Morsel revenue: price * quantity.
        raw = daily_sales.copy()
        raw.columns = [col.strip().lower() for col in raw.columns]

        pink_sales = raw.loc[raw["product"].str.lower() == "pink morsel"].copy()
        pink_sales["date"] = pd.to_datetime(pink_sales["date"], format="mixed", errors="coerce")
        pink_sales["price"] = (
            pink_sales["price"].astype(str).str.replace("$", "", regex=False).astype(float)
        )
        pink_sales["sales"] = pink_sales["price"] * pink_sales["quantity"]

        grouped_sales = (
            pink_sales.dropna(subset=["date"]).groupby("date", as_index=False)["sales"].sum().rename(
                columns={"date": "Date", "sales": "Sales"}
            ).sort_values("Date")
        )

    grouped_sales["Period"] = grouped_sales["Date"].apply(
        lambda date: "Before 2021-01-15" if date < PRICE_INCREASE_DATE else "After 2021-01-15"
    )
    return grouped_sales


def build_figure(data: pd.DataFrame):
    before_avg = data.loc[data["Date"] < PRICE_INCREASE_DATE, "Sales"].mean()
    after_avg = data.loc[data["Date"] >= PRICE_INCREASE_DATE, "Sales"].mean()

    figure = px.line(
        data,
        x="Date",
        y="Sales",
        title=(
            "Total Daily Pink Morsel Sales\n"
            f"Average before: ${before_avg:,.2f} | Average after: ${after_avg:,.2f}"
        ),
        labels={"Date": "Date", "Sales": "Total Sales (USD)"},
    )

    marker_x = PRICE_INCREASE_DATE.strftime("%Y-%m-%d")
    figure.add_shape(
        type="line",
        x0=marker_x,
        x1=marker_x,
        y0=0,
        y1=1,
        xref="x",
        yref="paper",
        line={"dash": "dash", "width": 2, "color": "#B54708"},
    )
    figure.add_annotation(
        x=marker_x,
        y=1,
        xref="x",
        yref="paper",
        text="Price increase (2021-01-15)",
        showarrow=False,
        xanchor="left",
        yanchor="bottom",
    )

    figure.update_layout(
        title_x=0.5,
        template="plotly_white",
        margin={"l": 40, "r": 20, "t": 80, "b": 40},
    )
    return figure


def create_app() -> Dash:
    sales_data = load_daily_sales()
    figure = build_figure(sales_data)

    app = Dash(__name__)
    app.title = "Soul Foods Sales Visualiser"

    app.layout = html.Div(
        [
            html.H1("Soul Foods: Pink Morsel Sales Before vs After Price Increase"),
            dcc.Graph(figure=figure),
        ],
        style={"maxWidth": "1100px", "margin": "0 auto", "padding": "24px"},
    )

    return app


app = create_app()
server = app.server


if __name__ == "__main__":
    app.run(debug=True)
